name: Build Docker Images

on:
  workflow_dispatch:

jobs:
  test:
    name: Run Java Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x server/gradlew

      - name: Generate Gradle Wrapper
        run: cd server && gradle wrapper

      - name: Build with Gradle
        run: cd server && ./gradlew build

  build:
    name: Build Docker Images
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: client
            context: ./client
            dockerfile: ./client/Dockerfile
          - service: growth-calculation
            context: ./server
            dockerfile: ./server/src/growth-calculation/Dockerfile
          - service: content-ingestion
            context: ./server
            dockerfile: ./server/src/content-ingestion/Dockerfile
          - service: trend-dashboard
            context: ./server
            dockerfile: ./server/src/trend-dashboard/Dockerfile
          - service: monitoring
            context: ./server
            dockerfile: ./server/src/monitoring/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Install Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
