name: Deploy EC2 and Configure with Ansible

on:
  workflow_dispatch:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init and Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve > tf.log
        IP=$(terraform output -raw public_ip)
        echo "EC2_IP=$IP" >> $GITHUB_ENV

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Wait for EC2 SSH
      run: |
        for i in {1..20}; do
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$EC2_IP "echo connected" && break
          sleep 10
        done

    - name: Run Ansible
      run: |
        ansible-playbook ansible/playbook.yml -i "$EC2_IP," -u ec2-user --private-key ~/.ssh/id_rsa
