name: Deploy 2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Debug AWS Credentials # Add this step
      run: |
        echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
        if [ -n "$AWS_ACCESS_KEY_ID" ]; then echo "AWS_ACCESS_KEY_ID is set"; else echo "AWS_ACCESS_KEY_ID is NOT set"; fi
        # Use a less revealing check for the secret key itself in logs
        if [ -n "$AWS_SECRET_ACCESS_KEY" ]; then echo "AWS_SECRET_ACCESS_KEY is partially set (checking length > 0)"; else echo "AWS_SECRET_ACCESS_KEY is NOT set"; fi
        if [ -n "$AWS_SESSION_TOKEN" ]; then echo "AWS_SESSION_TOKEN is set"; else echo "AWS_SESSION_TOKEN is NOT set (this is OK if using IAM User creds)"; fi
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
    
    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve | tee tf.log
        IP=$(terraform output -raw instance_ip)
        echo "EC2_IP=$IP" >> $GITHUB_ENV

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Wait for EC2 SSH
      run: |
        for i in {1..20}; do
          echo "Waiting for EC2 to become reachable (try $i)..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$EC2_IP "echo connected" && break
          sleep 10
        done

    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible/playbook.yml -i "$EC2_IP," -u ec2-user --private-key ~/.ssh/id_rsa
